version: '3'
services:
  server-mongo-rust:
    image: server-mongo-rust
    build: ./server-mongo-rust
    volumes:
      - ./server-mongo-rust:/app
    # args:
    #   - DATABASE_URL: mongodb://db_mongo:27020
    ports:
      - "4000:4000"
    depends_on:
      - db_mongo
  client-reactjs:
    image: client-reactjs
    build: ./client-reactjs
    volumes:
      - ./client-reactjs:/app
    ports:
      - "3001:3001"
  db_mongo:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - ./data:/data/db
